spring:
    profiles.active: mysql

    application.name: Virtual Clinic

    mvc.dispatch-options-request: true

    jpa:
        show-sql: true
        properties.hibernate.format_sql: true

---
custom:
    cors:
        allow-origin: "${ALLOW_ORIGINS:http://localhost:3000}"
        allow-methods: "GET, POST, PATCH, PUT, DELETE, OPTIONS"
        allow-credentials: "true"
        allow-headers: "Access-Control-Allow-Headers, Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization"


