spring:
    jpa:
        hibernate.ddl-auto: none #create
        database: mysql
        #defer-datasource-initialization: true

    datasource:
        url: ${DB_URL:jdbc:mysql://localhost:3306/virtual_clinic}
        username: ${DB_USER:user}
        password: ${DB_PASSWORD:password}
        driver-class-name: com.mysql.cj.jdbc.Driver
